version: '3'
services:
  db:
    image: mysql:latest
    container_name: local-mysql-forum
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./Development_db:/var/lib/mysql
