version: '3'
services:
  db:
    image: mysql:latest
    container_name: local-mysql-forum
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Br41nsc00l#12
      - MYSQL_DATABASE=forum
    volumes:
      - C:/Users/Gilang/go/Development/Development_db:/var/lib/mysql
